spring:
  application:
    name: patient-registry

#DatasourceConfiguration
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: c##premsai
    password: prem123
    driver-class-name: oracle.jdbc.driver.OracleDriver

#JpaConfiguration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

#DevToolsConfiguration
  devtools:
    restart:
      enabled: true

#ServerConfiguration
server:
  port: 9999
  servlet:
    context-path: /premit

