logging.file.name=application.log
server.port=9999
server.servlet.context-path=/premit
spring.application.name=patient-registry
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=c##premsai
spring.datasource.password=prem123
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.devtools.restart.enabled=true

logging.level.org.springframework=debug
logging.level.com.premit.patient_registry=debug